from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("api/terms/suggest/", views.term_suggest, name="term_suggest"),
    path("api/terms/exists/", views.term_exists, name="term_exists"),
    path("api/prescriptions/templates/", views.prescription_template_payload, name="prescription_template_payload"),
    path("api/scales/templates/", views.scale_template_payload, name="scale_template_payload"),
    path("accounts/", views.account_list, name="account_list"),
    path("templates/manage/", views.template_manage, name="template_manage"),
    path("terms/", views.term_list, name="term_list"),
    path("terms/<int:pk>/edit/", views.term_update, name="term_update"),
    path("terms/<int:pk>/delete/", views.term_delete, name="term_delete"),
    path("prescriptions/", views.prescription_template_list, name="prescription_template_list"),
    path("prescriptions/<int:pk>/edit/", views.prescription_template_update, name="prescription_template_update"),
    path("prescriptions/<int:pk>/delete/", views.prescription_template_delete, name="prescription_template_delete"),
    path("scales/", views.scale_template_list, name="scale_template_list"),
    path("scales/<int:pk>/edit/", views.scale_template_update, name="scale_template_update"),
    path("scales/<int:pk>/delete/", views.scale_template_delete, name="scale_template_delete"),
    path("accounts/new/", views.account_create, name="account_create"),
    path("accounts/<int:pk>/edit/", views.account_update, name="account_update"),
    path("accounts/<int:pk>/delete/", views.account_delete, name="account_delete"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/new/", views.project_create, name="project_create"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path(
        "projects/<int:pk>/enrollments/<int:enrollment_id>/delete/",
        views.project_enrollment_delete,
        name="project_enrollment_delete",
    ),
    path(
        "projects/<int:pk>/enrollments/<int:enrollment_id>/marker/",
        views.project_enrollment_marker_update,
        name="project_enrollment_marker_update",
    ),
    path("projects/<int:pk>/edit/", views.project_update, name="project_update"),
    path("projects/<int:pk>/delete/", views.project_delete, name="project_delete"),
    path("projects/<int:pk>/export/", views.project_export, name="project_export"),
    path("projects/<int:pk>/export/detail/", views.project_export_detail, name="project_export_detail"),
    path("", views.patient_list, name="patient_list"),
    path("patients/export/", views.patient_export, name="patient_export"),
    path("patients/export/detail/", views.patient_export_detail, name="patient_export_detail"),
    path("patients/new/", views.patient_create, name="patient_create"),
    path("patients/<int:pk>/edit/", views.patient_update, name="patient_update"),
    path("patients/<int:pk>/delete/", views.patient_delete, name="patient_delete"),
    path("patients/<int:pk>/ai-chat/", views.patient_ai_chat, name="patient_ai_chat"),
    path("patients/<int:pk>/", views.patient_detail, name="patient_detail"),
    path(
        "patients/<int:patient_pk>/treatments/new/",
        views.treatment_create,
        name="treatment_create",
    ),
    path("treatments/<int:pk>/edit/", views.treatment_update, name="treatment_update"),
    path("treatments/<int:pk>/delete/", views.treatment_delete, name="treatment_delete"),
    path(
        "treatments/<int:pk>/toggle-followup/",
        views.treatment_toggle_followup,
        name="treatment_toggle_followup",
    ),
    path(
        "treatments/<int:treatment_id>/followups/new/",
        views.followup_create,
        name="followup_create",
    ),
    path("followups/<int:pk>/edit/", views.followup_update, name="followup_update"),
    path("followups/<int:pk>/delete/", views.followup_delete, name="followup_delete"),
    path(
        "attachments/<int:pk>/download/",
        views.auxiliary_attachment_download,
        name="auxiliary_attachment_download",
    ),
    path(
        "attachments/<int:pk>/preview/",
        views.auxiliary_attachment_preview,
        name="auxiliary_attachment_preview",
    ),
    path(
        "attachments/<int:pk>/delete/",
        views.auxiliary_attachment_delete,
        name="auxiliary_attachment_delete",
    ),
]
