# Generated by Django 5.2.12 on 2026-04-14 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0014_auxiliary_attachment_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalterm',
            name='category',
            field=models.CharField(choices=[('herb', '中药饮片'), ('tcm_disease', '中医疾病'), ('western_disease', '西医疾病'), ('treatment_principle', '治则治法'), ('pathogenesis', '病因病机'), ('symptom', '症状/证候')], max_length=50, verbose_name='术语分类'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='就诊单位'),
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='项目名称')),
                ('principal_investigator', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成')], default='active', max_length=20, verbose_name='项目状态')),
                ('target_enrollment', models.PositiveIntegerField(default=0, verbose_name='目标例数')),
                ('notes', models.TextField(blank=True, verbose_name='项目备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_research_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '研究项目',
                'verbose_name_plural': '研究项目',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=60, verbose_name='项目分组')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='入组日期')),
                ('notes', models.TextField(blank=True, verbose_name='入组备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_enrollments', to='followup.patient', verbose_name='患者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='followup.researchproject', verbose_name='研究项目')),
            ],
            options={
                'verbose_name': '项目入组记录',
                'verbose_name_plural': '项目入组记录',
                'ordering': ['-enrollment_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'patient'), name='unique_project_patient_enrollment')],
            },
        ),
    ]
