# Generated by Django 5.2.12 on 2026-04-14 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0017_project_enrollment_marker_status_simplify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['treatment', '-visit_number', '-followup_date'], name='idx_followup_latest'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', '-start_date', '-created_at'], name='idx_treat_patient_latest'),
        ),
    ]
