# Generated by Django 5.2.12 on 2026-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0018_followup_idx_followup_latest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_projects',
            field=models.ManyToManyField(blank=True, related_name='authorized_user_profiles', to='followup.researchproject', verbose_name='可管理项目'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modify_window_days',
            field=models.PositiveIntegerField(blank=True, help_text='管理员和普通账号默认均为 3 天。', null=True, verbose_name='可修改/删除历史数据天数'),
        ),
    ]
